version: '3.7'

networks:
  app-tier:
    driver: bridge

services:

    postgres:
        image: postgres:9.6
        container_name: postgres_container
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    airflow:
        build: './airflow'
        container_name: airflow_container
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ../dags:/usr/local/airflow/dags
            - ../data:/usr/local/airflow/data
            - ../models:/usr/local/airflow/models
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper_container
        ports:
            - "2181:2181"
        networks:
            - app-tier
    kafka:
        image: wurstmeister/kafka
        container_name: kafka_container
        ports:
            - "9092:9092"
            - "29092:29092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_CREATE_TOPICS: "TopicA:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_BROKER_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - app-tier

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    # mlflow:
    #     build: './mlflow'
    #     container_name: mlflow_container
    #     ports:
    #         - "5000:5000"
    #     command: 'mlflow server --backend-store-uri ./mlflow --host 0.0.0.0 --port 5000'

